services:
  - type: web
    name: genesis-site
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: genesis123
